#Makefile generated by amake
#On Thu Dec 20 08:06:06 2018
#To print amake help use 'amake --help'.
CC=gcc
CPPC=g++
LINK=g++
SRCDIR=src
OBJDIR=obj
FLAGS=-g -Wall -std=c++11 
LIBS=-lssl -lcrypto 
OBJS=$(OBJDIR)/io.o $(OBJDIR)/main.o $(OBJDIR)/layout.o 
EXEC=mhw-save-editor
DATE=$(shell date +"%Y-%m-%d")

$(EXEC) : $(OBJS)
	$(LINK) $(OBJS) -o $(EXEC) $(FLAGS) $(LIBS)

$(OBJDIR)/io.o: src/io.cpp src/io.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/io.cpp -c -o $@

$(OBJDIR)/main.o: src/main.cpp src/io.h src/layout.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/main.cpp -c -o $@

$(OBJDIR)/layout.o: src/layout.cpp src/layout.h src/io.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/layout.cpp -c -o $@

$(OBJDIR)/__setup_obj_dir :
	mkdir -p $(OBJDIR)
	touch $(OBJDIR)/__setup_obj_dir

.PHONY: clean bzip release

clean :
	rm -rf $(OBJDIR)/*.o
	rm -rf $(EXEC)

bzip :
	tar -cvf "$(DATE).$(EXEC).tar" $(SRCDIR)/* Makefile
	bzip2 "$(DATE).$(EXEC).tar"

release : FLAGS +=-O3 -D_RELEASE
release : $(EXEC)

